plugins {
    id "com.android.application"
}

android {
    namespace "fr.bywilly.counter"
    compileSdk 36

    defaultConfig {
        applicationId "fr.bywilly.counter"
        minSdk 23
        targetSdk 36
        versionCode 1
        versionName "1.0.0"

        resourceConfigurations += ["fr"]
    }

    buildTypes {
        debug {
            applicationIdSuffix ".debug"
            versionNameSuffix "-debug"
        }
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildFeatures {
        buildConfig false
    }

    lint {
        abortOnError true
        checkDependencies true
        checkReleaseBuilds true
        warningsAsErrors false
    }
}

dependencies {
    implementation "com.google.androidbrowserhelper:androidbrowserhelper:2.7.3"
}
